# ************************************************************
#
# Database: externalassments
# Generation Time: 2019-12-04 10:53:58 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table sat_data
# ------------------------------------------------------------

DROP TABLE IF EXISTS `sat_data`;

CREATE TABLE `sat_data` (
  `SAT_DataKey` int(11) NOT NULL AUTO_INCREMENT,
  `AI_CODE` int(11) NOT NULL,
  `AI_NAME` varchar(23) NOT NULL,
  `FILLER_1` varchar(30) DEFAULT NULL,
  `COHORT_YEAR` int(11) NOT NULL,
  `DISTRICT_NAME` varchar(30) DEFAULT NULL,
  `NAME_LAST` varchar(13) NOT NULL,
  `NAME_FIRST` varchar(12) NOT NULL,
  `NAME_MI` varchar(1) DEFAULT NULL,
  `SEX` varchar(1) NOT NULL,
  `RACE_ETH_CUBAN` varchar(1) DEFAULT NULL,
  `RACE_ETH_MEXICAN` varchar(1) DEFAULT NULL,
  `RACE_ETH_PUERTORICAN` varchar(30) DEFAULT NULL,
  `RACE_ETH_HISP_LAT` varchar(1) DEFAULT NULL,
  `RACE_ETH_NON_HISP_LAT` varchar(1) DEFAULT NULL,
  `RACE_ETH_INDIAN_ALASKAN` varchar(1) DEFAULT NULL,
  `RACE_ETH_ASIAN` varchar(1) DEFAULT NULL,
  `RACE_ETH_AFRICANAMERICAN` varchar(1) DEFAULT NULL,
  `RACE_ETH_HAWAIIAN_PI` varchar(1) DEFAULT NULL,
  `RACE_ETH_WHITE` varchar(1) DEFAULT NULL,
  `RACE_ETH_OTHER` varchar(30) DEFAULT NULL,
  `FILLER_2` varchar(30) DEFAULT NULL,
  `DERIVED_AGGREGATE_RACE_ETH` int(11) NOT NULL,
  `BIRTH_DATE` date NOT NULL,
  `FILLER_3` varchar(30) DEFAULT NULL,
  `CB_ID` int(11) NOT NULL,
  `SECONDARY_ID` int(11) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(46) NOT NULL,
  `ADDRESS_LINE2` varchar(36) DEFAULT NULL,
  `ADDRESS_CITY` varchar(14) NOT NULL,
  `ADDRESS_STATE` varchar(2) DEFAULT NULL,
  `ADDRESS_ZIP` int(11) DEFAULT NULL,
  `ADDRESS_COUNTY` int(11) DEFAULT NULL,
  `ADDRESS_COUNTRY` varchar(2) NOT NULL,
  `ADDRESS_PROVINCE` varchar(30) DEFAULT NULL,
  `FOREIGN_ADDRESS` varchar(1) DEFAULT NULL,
  `PHONE` varchar(30) DEFAULT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `HOMESCHOOL` varchar(30) DEFAULT NULL,
  `STUDENT_SEARCH_SERVICE` varchar(1) DEFAULT NULL,
  `PROJ_GRAD_DATE` varchar(7) DEFAULT NULL,
  `SAA` varchar(30) DEFAULT NULL,
  `LATEST_REGISTRATION_NUM` int(11) DEFAULT NULL,
  `LATEST_MAKE_UP` varchar(30) DEFAULT NULL,
  `LATEST_ASSESSMENT_DATE` date DEFAULT NULL,
  `LATEST_GRADE_LEVEL` int(11) DEFAULT NULL,
  `LATEST_REVISED` varchar(30) DEFAULT NULL,
  `LATEST_SAT_TOTAL` int(11) DEFAULT NULL,
  `LATEST_SAT_EBRW` int(11) DEFAULT NULL,
  `LATEST_SAT_MATH_SECTION` int(11) DEFAULT NULL,
  `LATEST_SAT_READING` int(11) DEFAULT NULL,
  `LATEST_SAT_WRIT_LANG` int(11) DEFAULT NULL,
  `LATEST_SAT_MATH_TEST` decimal(4,1) DEFAULT NULL,
  `LATEST_SAT_SCI_CROSS` int(11) DEFAULT NULL,
  `LATEST_SAT_HIST_SOCST_CROSS` int(11) DEFAULT NULL,
  `LATEST_SAT_WORDS_CONTEXT` int(11) DEFAULT NULL,
  `LATEST_SAT_COMM_EVIDENCE` int(11) DEFAULT NULL,
  `LATEST_SAT_EXPR_IDEAS` int(11) DEFAULT NULL,
  `LATEST_SAT_ENG_CONVENT` int(11) DEFAULT NULL,
  `LATEST_SAT_HEART_ALGEBRA` int(11) DEFAULT NULL,
  `LATEST_SAT_ADV_MATH` int(11) DEFAULT NULL,
  `LATEST_SAT_PROBSLV_DATA` int(11) DEFAULT NULL,
  `LATEST_SAT_ESSAY_READING` int(11) DEFAULT NULL,
  `LATEST_SAT_ESSAY_ANALYSIS` int(11) DEFAULT NULL,
  `LATEST_SAT_ESSAY_WRITING` int(11) DEFAULT NULL,
  `FILLER_4` varchar(30) DEFAULT NULL,
  `LATEST_SAT_CRITICAL_READING` int(11) DEFAULT NULL,
  `LATEST_SAT_MATH` int(11) DEFAULT NULL,
  `LATEST_SAT_WRITING` int(11) DEFAULT NULL,
  `LATEST_SAT_ESSAY` int(11) DEFAULT NULL,
  `LATEST_SAT_ESSAY_MC` int(11) DEFAULT NULL,
  `FILLER_5` varchar(30) DEFAULT NULL,
  `FILLER_6` varchar(30) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_TOTAL` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_EBRW` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_MATH_SECTION` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_READING` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_WRIT_LANG` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_MATH_TEST` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_SCI_CROSS` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_HIST_SOCST_CROSS` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_WORDS_CONTEXT` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_COMM_EVIDENCE` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_EXPR_IDEAS` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_ENG_CONVENT` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_HEART_ALGEBRA` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_ADV_MATH` int(11) DEFAULT NULL,
  `PERCENTILE_NATREP_SAT_PROBSLV_DATA` int(11) DEFAULT NULL,
  `PERCENTILE_CBSNATION_SAT_CRITICAL_READING` int(11) DEFAULT NULL,
  `PERCENTILE_CBSNATION_SAT_MATH` int(11) DEFAULT NULL,
  `PERCENTILE_CBSNATION_SAT_WRITING` int(11) DEFAULT NULL,
  `FILLER_7` varchar(30) DEFAULT NULL,
  `FILLER_8` varchar(30) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_TOTAL` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_EBRW` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_MATH_SECTION` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_READING` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_WRIT_LANG` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_MATH_TEST` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_SCI_CROSS` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_HIST_SOCST_CROSS` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_WORDS_CONTEXT` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_COMM_EVIDENCE` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_EXPR_IDEAS` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_ENG_CONVENT` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_HEART_ALGEBRA` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_ADV_MATH` int(11) DEFAULT NULL,
  `PERCENTILE_NATUSER_SAT_PROBSLV_DATA` int(11) DEFAULT NULL,
  `PERCENTILE_CBSSTATE_SAT_CRITICAL_READING` varchar(30) DEFAULT NULL,
  `PERCENTILE_CBSSTATE_SAT_MATH` varchar(30) DEFAULT NULL,
  `PERCENTILE_CBSSTATE_SAT_WRITING` varchar(30) DEFAULT NULL,
  `FILLER_9` varchar(30) DEFAULT NULL,
  `FILLER_10` varchar(30) DEFAULT NULL,
  `EBRW_CCR_BENCHMARK` varchar(1) DEFAULT NULL,
  `MATH_CCR_BENCHMARK` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`SAT_DataKey`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
